-- Généré automatiquement à partir de liste_panne_source.txt par parse_pannes.mjs
-- Ne pas éditer directement ce fichier de seed initial : utilisez l'interface
-- "Gérer la liste des pannes" de l'application pour les mises à jour futures,
-- ou relancez ce script après avoir modifié liste_panne_source.txt.

insert into panne_types (code, description, active)
values
('1', 'Operating system exception detected', true),
('1', 'Unhandled C++ exception', true),
('1', 'DeleveryInterfaceClinicalState: One or more calibration files are missing (need calibration) or not committed. RDS los has more details', true),
('1', 'kVcollimatorPrepareFragmentState : no working controler', true),
('2', 'a PCP has failed the watchdog', true),
('2', 'MMPS not online', true),
('2', 'A required SSM device is not onlinge', true),
('3', 'Beamline devices offline : AFC on ICA off MMPS on IPPS on SSM on', true),
('3', 'Couch failed to initialize : 180seconds time out', true),
('3', 'Timed out waiting for HW OK signal', true),
('4', 'Motion procedure or radiograph is required, but kv is disavled, possibly missing hardware', true),
('8', 'failed to setup procedure: failed to setup procedure', true),
('8', 'KVTriggerPrepareFragmentState : doWork', true),
('8', 'Detector kV fault', true),
('8', 'KvDetector run procedure failed', true),
('24', 'MonitorSafety Status: Emergency stop button pressed', true),
('25', 'BeamLine runRadiation : SSM Fault', true),
('25', 'Beamline devices offline : AFC on, ICA off, MMPS on, IPPS on, SSM on', true),
('25', 'BeamLiveTask::HardwareOkEventHandler, Hardware Ok Fault, generating FAULT_MACHINE', true),
('26', 'Dose chamber B to A : average value out of range timeout expired', true),
('26', 'Beamline ::: RunRadiation: performance tolerance fault', true),
('26', 'Beamlinetask::subsystemerror:dose Chamber A: average value out of range, timeout expired', true),
('26', 'dose chamber B : average value out of range timeout expired', true),
('26', 'Dose Chamber 1 - average value out-of-range, timeout expired', true),
('31', 'Failed to set magnetronMagnet to 180000mA', true),
('31', 'Failed to set magnetronMagnet to 1600 mA', true),
('38', 'DCS: CCPS value outside of control range limits of 810.314 to 831.541 for > 5 seconds.', true),
('42', 'Tscan position error over tolerance', true),
('43', 'test2: final leaf positional fault', true),
('43', 'initTest : no leaf was opened, check MLC hardware and MLC air pressure', true),
('', '45 : monitor safety status : interlock is open', true),
('47', 'PTP monitor fault', true),
('47', 'StationarySafetyWaitForReadyState: has watchdog fault when entering critical state', true),
('47', 'Watchdog Fault:KvGenerator_RadiatePrep on RCS has a watchdog timeout', true),
('47', 'Watchdog Fault:Raw_Data_Collectorbeamlinestatusdatawatchdog on SCS has a watchdog timeout', true),
('47', 'RotationalSafetyWaitForReadyState: has watchdog fault when entering critical state', true),
('47', 'watchdog fault : kv collimator on RCShas a subsystem watchdog timeout', true),
('47', 'watchdog fault : beamtrigger on RCS has a subsystem watchdog time out', true),
('49', 'MonitorSafetyStatus - PDU OK Signals indicate voltage are outside of acceptable ranges', true),
('49', 'Monior SafetyStatus: PDU OK signal indicates voltages are outside of acceptable ranges', true),
('50', 'Monitor safety status/pdu standly button has been pressed', true),
('52', 'the requiest/correct imputs were not found-key position likely', true),
('54', 'Unable to set couch button panel', true),
('54', 'monitorThread : Failed to turn off keypad controls', true),
('', '54 SYSTEM FAUTE', true),
('54', 'Couch error in setting Y position', true),
('54', 'Couch error in setting Z position', true),
('58', 'LaserWaitForEncounterState: Error moving lasers to 0.0', true),
('58', 'LaserTask::homePositionOnThread:ProcedureFault-Failed to move lasers to desired position. Logs have amount.', true),
('64', 'Gantry error: STATUS_NO_ERROR, drive error: Software Error', true),
('79', '2786335,4194305,4194305,4194305 : Jaw subsystem indicates it is in a faulted state, recovery must be attempted', true),
('79', 'JawPreapare Fragment State : std Bad Alloc', true),
('79', '2786315-2786298 : JawWaitForReadyState // Driver Exception - Verifiy Calibration failed, Jaw needs calibration', true),
('79', '2786335-4194305-4194305-4194305 : Jaw subsistem indicates it is in a faulted state, recovery must be attempted', true),
('79', '2786348-2786348…. JawRadiateStateException… Jaw profile aborted due to an error', true),
('79', '2786315,-1:Jaw Faults could not be recovered from', true),
('79', '2786321, 2786323 : Jaw faults could not recovered from', true),
('79', '2786315,2786320,2786315, 2786315, 2786335, … subsystem indicates it is in fault state, recovery must be attempted', true),
('79', '2786321,2786323 : Jaw Faults could not be revored from', true),
('81', 'RawDATARadiation : streaming error, failed to prepare processed detector blocks', true),
('81', 'RawData: streaming error', true),
('83', 'Rawdata Task data timeout in Rawdata receive channel', true),
('', '85 DASRRADIATIONSTATE DAS packet total errors', true),
('87', 'BeamTriggerRadiationState : Primary Procedure Monitor failed', true),
('89', 'Failed to cancel previous kv generator task for new encounter', true),
('89', '/mnt/jenkins/workspace /RDS/Europa_3.0.0.10_Embedded/RD….output tolerance', true),
('90', '/mnt/jenkins/workspace/RDS/Europa_3.0.0.10_Embedded/RD to confirm setting anode speed', true),
('90', 'Attempting to start a procedure that requires Unavailable kV Hardware', true),
('93', 'Kv Generator Faulted', true),
('93', '/mnt/jenkins/workspace/RDS/Europa_3,0,0,10_Embedded/RD Generator Raised an event', true),
('54', 'Unsolicited move loc: Z1 ctrlr (Base) Error code (140F)', true),
('100', 'TDCS initiated fault: Received STOP_PROCEDURE This causes faultProcedure to be fired', true),
('105', 'kVTriggerTaskTask::kVTriggerMonitorErrcallback - Detector trigger received unexpectedly', true),
('105', 'KVTriggerRadiationState : doWork - Failed to run scheduled Kvct', true),
('108', 'KVDetector ActuatorTask::errorCallback-Galil Amplifier Status ( Peak current)', true),
('108', 'KVDetector ActuatorWaitForReadyState::doWork - Kv Detector actuator application disabled', true),
('108', 'KVDetector Actuator Post Fragment State : Do Work - Failed to stop motion', true),
('112', 'TDCS', true),
('', 'SERVICE CODE 0D281344', true),
('', 'SERVICE CODE 6E8F34F0', true),
('', 'SERVICE CODE SYSTÈME ERROR B2B38097', true),
('', 'SERVICE CODE SYSTÈME ERROR 3C231669', true),
('', 'SERVICE CODE SYSTÈME ERROR 7CF35CBF', true),
('', 'System error Service code 0D281344', true),
('', 'The emergency Stop button is pressed', true),
('', 'The machine is not connected', true),
('', 'The machine has encountered multiple faults and is attempting to reset itself,', true),
('', 'écran figé', true),
('', 'Machine unexpectedly disconnected', true),
('', 'Porte du bunker', true),
('', 'Erreur de communication DICOM', true),
('', 'MLC leaf is in the wrong position', true),
('', 'machine s''est coupée avant connexion à TDC', true),
('', 'Critical Error (ID 7AC3626D)', true),
('', 'aucun message sur la TDC <-> exctinction non voulue de la radixact PCP éteints', true),
('108', 'KVDETECTORActuator task:::errorcallback- Galil Axis Specific Error Word (0x2018- Galil Digittal Motion Controller (DMC)-Axis Specific-over velocity condition detected)', true),
('108', 'KVDetectorActuatorPrepareFragmentState::doWork-Kv Detector Actuator application disabled', true)
on conflict do nothing;
